name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}S—Å
          
  docker:
    name: Build and push docker image
    needs: [superlint]
    runs-on: ubuntu-latest
 
    steps:
      - name: Set up QEMU
        uses: actions/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: spetrushevska/kiiilab:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
